name=CATMOUSE
version=1.0.0
author=OPT-OUT
maintainer=OPT-OUT
sentence=Asymmetric ESP-NOW Channel Hopping Game Protocol.
paragraph=A cat-and-mouse channel hopping networking library. The Mouse hides on random Wi-Fi channels for dynamic intervals, and the Cat rapidly sweeps the spectrum to find it via ESP-NOW.
category=Communication
url=https://github.com/0P7-0U7/CATMOUSE
architectures=esp32
includes=CatMouse.h
license=CNPL v4
